name: Run tests

on:
  push:
    branches: [ main ]
    paths:
      - 'tests/**.py'
      - 'src/**.py'
      - setup.cfg
      - .github/workflows/tests.yml
      - requirements-test.txt
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v1.2.0
    with:
      cover_package: src/matchbox
      python-versions: '["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]'
